CREATE TABLE DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW(
ID VARCHAR2(32),
CERTIFICAT_INS_ID VARCHAR2(32),
CREATE_TIME DATETIME,
UPDATE_TIME DATETIME,
DATA_SOURCE CHAR(1),
LIC_NO VARCHAR2(50),
FOOD_OPER_NAME VARCHAR2(200),
UNI_SC_CODE VARCHAR2(50),
LE_REP VARCHAR2(200),
ECONOMIC_NATURE VARCHAR2(1),
QTJJXZBM VARCHAR2(20),
QTJJXZ VARCHAR2(20),
DOM VARCHAR2(500),
OPER_LOC_CODE VARCHAR2(50),
OPER_LOC_NAME VARCHAR2(50),
JYCSDZYZSSFYZ VARCHAR2(20),
OPER_LOC VARCHAR2(500),
PHYSICAL_STORES VARCHAR2(1),
SPXSJCYFWCSSYMJ VARCHAR2(20),
SFSYCK VARCHAR2(50),
FORMS_CATEGORY VARCHAR2(20),
MAIN_BUS_FOR_CODE VARCHAR2(10),
MAIN_BUS_FOR VARCHAR2(500),
ND_MAIN_BUS_FOR_CODE VARCHAR2(50),
ND_MAIN_BUS_FOR VARCHAR2(500),
MAIN_BUS_FOR_DETAILS VARCHAR2(2000),
BUS_ITEM_DETAILS VARCHAR2(2000),
FB_BUS_ITEM_DETAILS VARCHAR2(2000),
SPXSMS VARCHAR2(50),
STJYMS VARCHAR2(50),
LYZDSBCSSPJY VARCHAR2(20),
SCHOOL_CONTRACT_UNISCID VARCHAR2(64),
SCHOOL_CONTRACT_NAME VARCHAR2(200),
SCHOOL_CONTRACTJYXKZBH VARCHAR2(50),
CHILD_CARE_CONTRACT_UNISCID VARCHAR2(50),
CHILD_CARE_CONTRACT_NAME VARCHAR2(50),
CHILD_CARE_CONTRACTJYXKZBH VARCHAR2(50),
ETC_CONTRACT_UNISCID VARCHAR2(64),
ETC_CONTRACT_NAME VARCHAR2(500),
ETC_CONTRACTJYXKZBH VARCHAR2(64),
QTSPMS VARCHAR2(500),
HDSPCLQMJ VARCHAR2(10),
HDZDJCRS INT,
HDDCZDGCRS INT,
SFCSWLJY VARCHAR2(10),
SYZJWZ VARCHAR2(10),
WEBSITE VARCHAR2(500),
TGWLSPJYDSFPTJY VARCHAR2(10),
PTMC VARCHAR2(200),
SYQT VARCHAR2(10),
QTWLJYFS VARCHAR2(100),
SYWD VARCHAR2(10),
WDMC VARCHAR2(100),
EWMFWLJ VARCHAR2(200),
QR_CODE VARCHAR2(500),
IS_ONSITE_VERIFICATION VARCHAR2(10),
EXEMPTION_ONSITE_INSPECTION VARCHAR2(255),
ISS_AUTH VARCHAR2(100),
ISS_AUTH_UNI_SCID VARCHAR2(20),
ISS_CERT_DATE DATE,
VAL_FROM DATE,
VALID_PER DATE,
LICENSE_STATUS VARCHAR2(2),
SUP_PHONE_NO INT,
ELECRTONIC_CERT_FLAG VARCHAR2(1),
LICENSE_CODE VARCHAR2(200),
OPSCO_TYPE_CODE VARCHAR2(10),
OPSCO_TYPE VARCHAR2(10),
PROCESS_DATE DATE,
DATE_BASE_TIME DATETIME,
DW_ETL_CREATE_TIME TIMESTAMP,
DW_ETL_UPDATE_TIME TIMESTAMP,
CONSTRAINT "BIZ_SPJYXKZ_ANALYZE_NEW_ID" NOT CLUSTER PRIMARY KEY (ID)
);
COMMENT ON TABLE DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW IS '食品经营许可证-JOSN结构表';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ID IS '主键';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.CERTIFICAT_INS_ID IS '证照实例id';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.DATA_SOURCE IS '数据来源 1-本系统 2-浪潮历史数据';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.LIC_NO IS '许可证编号';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.FOOD_OPER_NAME IS '经营者名称';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.UNI_SC_CODE IS '社会信用代码（身份证号码）';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.LE_REP IS '法定代表人（负责人）';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ECONOMIC_NATURE IS '经济性质（主体类型）1-企业 2-个体工商户 3-农民专业合作社 4-其他';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.QTJJXZBM IS '其他经济性质补充代码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.QTJJXZ IS '其他经济性质补充名称';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.DOM IS '住所';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.OPER_LOC_CODE IS '经营场所所在地行政区划代码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.OPER_LOC_NAME IS '经营场所所在地行政区划名称';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.JYCSDZYZSSFYZ IS '经营场所地址与住所是否一致';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.OPER_LOC IS '经营场所';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.PHYSICAL_STORES IS '实体门店';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SPXSJCYFWCSSYMJ IS '食品销售及餐饮服务场所使用面积（平方米）';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SFSYCK IS '经营场所内设仓库';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.FORMS_CATEGORY IS '主体业态分类';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.MAIN_BUS_FOR_CODE IS '主体业态代码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.MAIN_BUS_FOR IS '主体业态';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ND_MAIN_BUS_FOR_CODE IS '二级主体业态编码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ND_MAIN_BUS_FOR IS '二级主体业态';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.MAIN_BUS_FOR_DETAILS IS '证照上主体业态信息';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.BUS_ITEM_DETAILS IS '证照上经营项目信息';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.FB_BUS_ITEM_DETAILS IS '证照上经营项目信息（副本）';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SPXSMS IS '食品销售模式';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.STJYMS IS '食堂经营模式';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.LYZDSBCSSPJY IS '利用自动设备从事食品经营';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SCHOOL_CONTRACT_UNISCID IS '学校承包食堂的承包企业统一社会信用代码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SCHOOL_CONTRACT_NAME IS '学校承包食堂的承包企业名称';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SCHOOL_CONTRACTJYXKZBH IS '学校承包食堂的承包企业食品经营许可证';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.CHILD_CARE_CONTRACT_UNISCID IS '托幼机构承包食堂的承包企业统一社会信用代码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.CHILD_CARE_CONTRACT_NAME IS '托幼机构承包食堂的承包企业名称';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.CHILD_CARE_CONTRACTJYXKZBH IS '托幼机构承包食堂的承包企业食品经营许可证编号';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ETC_CONTRACT_UNISCID IS '其他承包食堂的承包企业统一社会信用代码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ETC_CONTRACT_NAME IS '其他承包食堂的承包企业名称';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ETC_CONTRACTJYXKZBH IS '其他承包食堂的承包企业食品经营许可证编号';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.QTSPMS IS '其他食堂的详细描述';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.HDSPCLQMJ IS '核定食品处理区面积';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.HDZDJCRS IS '核定最大就餐人数';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.HDDCZDGCRS IS '核定单次最大供餐人数';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SFCSWLJY IS '是否从事网络经营';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SYZJWZ IS '使用自建网站';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.WEBSITE IS '网址';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.TGWLSPJYDSFPTJY IS '通过网络食品交易第三方平台经营';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.PTMC IS '平台名称';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SYQT IS '使用其他网络交易方式';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.QTWLJYFS IS '其他网络交易方式';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SYWD IS '是否通过其它网店经营';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.WDMC IS '网店名称';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.EWMFWLJ IS '二维码访问链接';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.QR_CODE IS '二维码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.IS_ONSITE_VERIFICATION IS '是否启动现场核查';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.EXEMPTION_ONSITE_INSPECTION IS '免予现场核查情形';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ISS_AUTH IS '发证机关';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ISS_AUTH_UNI_SCID IS '发证机关代码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ISS_CERT_DATE IS '发证日期';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.VAL_FROM IS '有效期自';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.VALID_PER IS '有效期至';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.LICENSE_STATUS IS '许可证状态';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.SUP_PHONE_NO IS '投诉举报电话';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.ELECRTONIC_CERT_FLAG IS '是否拥有电子证书';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.LICENSE_CODE IS '电子证照唯一标识码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.OPSCO_TYPE_CODE IS '业务类型代码';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.OPSCO_TYPE IS '业务类型';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.PROCESS_DATE IS '办结日期';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.DATE_BASE_TIME IS '入库时间';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.DW_ETL_CREATE_TIME IS 'ETL创建时间';
COMMENT ON COLUMN DC_PERMIT.BIZ_SPJYXKZ_ANALYZE_NEW.DW_ETL_UPDATE_TIME IS 'ETL更新时间';

CREATE TABLE DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM(
ID VARCHAR2(32),
CERTIFICAT_INS_ID VARCHAR2(32),
LIC_NO VARCHAR2(50),
FOOD_SALES VARCHAR2(1),
BULK_FOOD_SALES VARCHAR2(1),
IS_BULK_COOKED_FOOD_SALES VARCHAR2(1),
IS_NOT_BULK_COOKED_FOOD_SALES VARCHAR2(1),
BULK_AND_PRE_FOOD_SALES VARCHAR2(1),
IS_BULK_AND_PRE_FOOD_SALES VARCHAR2(1),
IS_NOT_BULK_AND_PRE_FOOD_SALES VARCHAR2(1),
FOOD_SERVICE VARCHAR2(1),
HOT_FOOD_SALES VARCHAR2(1),
COLD_FOOD_SALES VARCHAR2(1),
IS_COLD_CAKE_SALES VARCHAR2(1),
IS_NOT_COLD_CAKE_SALES VARCHAR2(1),
IS_COLD_MEAT_FOOD_SALES VARCHAR2(1),
IS_NOT_COLD_MEAT_FOOD_SALES VARCHAR2(1),
RAW_FOOD_SALES VARCHAR2(1),
SEMI_FINISHED_FOOD_SALES VARCHAR2(1),
SELF_DRINK_SALES VARCHAR2(1),
FOOD_BUSINESS_MANAG VARCHAR2(1),
FOOD_SALES_CHAIN_MANAG VARCHAR2(1),
FOOD_SERVICE_CHAIN_MANAG VARCHAR2(1),
FOOD_SERVICE_MANAG VARCHAR2(1),
HOT_FOOD_SIMPLE_SALE VARCHAR2(1),
SELF_DRINK_SIMPLE_SALE VARCHAR2(1),
COLD_FOOD_SIMPLE_SALE VARCHAR2(1),
DATE_BASE_TIME DATETIME,
DW_ETL_CREATE_TIME TIMESTAMP,
DW_ETL_UPDATE_TIME TIMESTAMP,
CONSTRAINT "GJZJ_SPJY_NEW_BUSITEM_ID" NOT CLUSTER PRIMARY KEY (ID)
);
COMMENT ON TABLE DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM IS '推送国家总局食品经营经营项目表';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.ID IS '主键';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.CERTIFICAT_INS_ID IS '证照实例id';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.LIC_NO IS '许可证编号';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.FOOD_SALES IS '食品销售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.BULK_FOOD_SALES IS '散装食品销售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.IS_BULK_COOKED_FOOD_SALES IS '含散装熟食销售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.IS_NOT_BULK_COOKED_FOOD_SALES IS '不含散装熟食销售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.BULK_AND_PRE_FOOD_SALES IS '散装食品和预包装食品销售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.IS_BULK_AND_PRE_FOOD_SALES IS '含散装熟食销售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.IS_NOT_BULK_AND_PRE_FOOD_SALES IS '不含散装熟食销售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.FOOD_SERVICE IS '餐饮服务';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.HOT_FOOD_SALES IS '热食类食品制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.COLD_FOOD_SALES IS '冷食类食品制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.IS_COLD_CAKE_SALES IS '含冷加工糕点制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.IS_NOT_COLD_CAKE_SALES IS '不含冷加工糕点制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.IS_COLD_MEAT_FOOD_SALES IS '含冷荤类食品制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.IS_NOT_COLD_MEAT_FOOD_SALES IS '不含冷荤类食品制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.RAW_FOOD_SALES IS '生食类食品制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.SEMI_FINISHED_FOOD_SALES IS '半成品制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.SELF_DRINK_SALES IS '自制饮品制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.FOOD_BUSINESS_MANAG IS '食品经营管理';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.FOOD_SALES_CHAIN_MANAG IS '食品销售连锁管理';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.FOOD_SERVICE_CHAIN_MANAG IS '餐饮服务连锁管理';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.FOOD_SERVICE_MANAG IS '餐饮服务管理';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.HOT_FOOD_SIMPLE_SALE IS '热食类食品制售是否简单制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.SELF_DRINK_SIMPLE_SALE IS '自制饮品制售是否简单制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.COLD_FOOD_SIMPLE_SALE IS '冷食类食品制售（除冷加工糕点制售和冷荤类食品制售之外）是否简单制售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.DATE_BASE_TIME IS '入库时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.DW_ETL_CREATE_TIME IS 'ETL创建时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_BUSITEM.DW_ETL_UPDATE_TIME IS 'ETL更新时间';

CREATE TABLE DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE(
ID VARCHAR2(32),
CERTIFICAT_INS_ID VARCHAR2(32),
LIC_NO VARCHAR2(50),
CHILD_CARE_CONTRACT_UNI_SCID VARCHAR2(18),
CHILD_CARE_CONTRACT_NAME VARCHAR2(500),
DATE_BASE_TIME DATETIME,
DW_ETL_CREATE_TIME TIMESTAMP,
DW_ETL_UPDATE_TIME TIMESTAMP,
CONSTRAINT "GJZJ_SPJY_NEW_CHILDCARE_ID" NOT CLUSTER PRIMARY KEY (ID)
);
COMMENT ON TABLE DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE IS '推送国家总局食品经营托幼机构食堂表';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE.ID IS '主键';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE.CERTIFICAT_INS_ID IS '证照实例id';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE.LIC_NO IS '许可证编号';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE.CHILD_CARE_CONTRACT_UNI_SCID IS '托幼机构承包食堂的承包企业统一社会信用代码';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE.CHILD_CARE_CONTRACT_NAME IS '托幼机构承包食堂的承包企业名称';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE.DATE_BASE_TIME IS '入库时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE.DW_ETL_CREATE_TIME IS 'ETL创建时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_CHILDCARE.DW_ETL_UPDATE_TIME IS 'ETL更新时间';

CREATE TABLE DC_PERMIT.GJZJ_SPJY_NEW_LE_REP(
ID VARCHAR2(32)，
CERTIFICAT_INS_ID VARCHAR2(32)，
LIC_NO VARCHAR2(50)，
LEREP VARCHAR2(200)，
CER_TYPE VARCHAR2(1)，
CER_NO VARCHAR2(100)，
TEL VARCHAR2(30)，
MOBILE VARCHAR2(30)，
FOOD_OPER_NAME VARCHAR2(500)，
UNI_SCID VARCHAR2(18)，
DATE_BASE_TIME DATETIME，
DW_ETL_CREATE_TIME TIMESTAMP,
DW_ETL_UPDATE_TIME TIMESTAMP,
CONSTRAINT "GJZJ_SPJY_NEW_LE_REP_ID" NOT CLUSTER PRIMARY KEY (ID)
);
COMMENT ON TABLE DC_PERMIT.GJZJ_SPJY_NEW_LE_REP IS '推送国家总局食品经营法人信息表';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.ID IS '主键';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.CERTIFICAT_INS_ID IS '证照实例id';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.LIC_NO IS '许可证编号';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.LEREP IS '姓名';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.CER_TYPE IS '证件类型';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.CER_NO IS '证件号、托幼机构供餐';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.TEL IS '固定电话';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.MOBILE IS '移动电话';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.FOOD_OPER_NAME IS '经营者名称';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.UNI_SCID IS '统一社会信用代码';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.DATE_BASE_TIME IS '入库时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.DW_ETL_CREATE_TIME IS 'ETL创建时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_LE_REP.DW_ETL_UPDATE_TIME IS 'ETL更新时间';

CREATE TABLE DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR(
ID VARCHAR2(32),
CERTIFICAT_INS_ID VARCHAR2(32),
LIC_NO VARCHAR2(50),
MAIN_BUS_FOR_CODE VARCHAR2(1),
MAIN_BUS_FOR VARCHAR2(500),
FOOD_WHOLESALE_SALES VARCHAR2(1),
CENTRAL_KIT VARCHAR2(1),
COLLECTIVE_DINING_DEL VARCHAR2(1),
AUTO_OPERATE VARCHAR2(1),
SCHOOL_SELF_CANTEEN VARCHAR2(1),
SCHOOL_CONTRACT_CANTEEN VARCHAR2(1),
CHILD_CARE_SELF_CANTEEN VARCHAR2(1),
CHILD_CARE_CONTRACT_CANTEEN VARCHAR2(1),
DATE_BASE_TIME DATETIME,
DW_ETL_CREATE_TIME TIMESTAMP,
DW_ETL_UPDATE_TIME TIMESTAMP,
CONSTRAINT "GJZJ_SPJY_NEW_MAINBUSFOR_ID" NOT CLUSTER PRIMARY KEY (ID)
);
COMMENT ON TABLE DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR IS '推送国家总局食品经营主体业态表';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.ID IS '主键';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.CERTIFICAT_INS_ID IS '证照实例id';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.LIC_NO IS '许可证编号';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.MAIN_BUS_FOR_CODE IS '主体业态代码';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.MAIN_BUS_FOR IS '主体业态';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.FOOD_WHOLESALE_SALES IS '食品批发销售';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.CENTRAL_KIT IS '中央厨房';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.COLLECTIVE_DINING_DEL IS '集体用餐配送';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.AUTO_OPERATE IS '利用自动设备从事食品经营';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.SCHOOL_SELF_CANTEEN IS '学校自营食堂';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.SCHOOL_CONTRACT_CANTEEN IS '学校承包食堂';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.CHILD_CARE_SELF_CANTEEN IS '托幼机构自营食堂';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.CHILD_CARE_CONTRACT_CANTEEN IS '托幼机构承包食堂';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.DATE_BASE_TIME IS '入库时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.DW_ETL_CREATE_TIME IS 'ETL创建时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_MAINBUSFOR.DW_ETL_UPDATE_TIME IS 'ETL更新时间';

CREATE TABLE DC_PERMIT.GJZJ_SPJY_NEW_REPORT(
ID VARCHAR2(32),
CERTIFICAT_INS_ID VARCHAR2(32),
LIC_NO VARCHAR2(50),
WAREHOUSE_ADDR VARCHAR2(1),
NETWORK_OPERATION VARCHAR2(1),
GROUP_MEAL_DIS VARCHAR2(1),
DATE_BASE_TIME DATETIME,
DW_ETL_CREATE_TIME TIMESTAMP,
DW_ETL_UPDATE_TIME TIMESTAMP,
CONSTRAINT "GJZJ_SPJY_NEW_REPORT_ID" NOT CLUSTER PRIMARY KEY (ID)
);
COMMENT ON TABLE DC_PERMIT.GJZJ_SPJY_NEW_REPORT IS '推送国家总局食品经营报告信息表';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.ID IS '主键';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.CERTIFICAT_INS_ID IS '证照实例id';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.LIC_NO IS '许可证编号';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.WAREHOUSE_ADDR IS '是否有外设仓库';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.NETWORK_OPERATION IS '是否网络经营';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.GROUP_MEAL_DIS IS '集体用餐配送单位是否向学校、托幼机构供餐';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.DATE_BASE_TIME IS '入库时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.DW_ETL_CREATE_TIME IS 'ETL创建时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_REPORT.DW_ETL_UPDATE_TIME IS 'ETL更新时间';

CREATE TABLE DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL(
ID VARCHAR2(32)，
CERTIFICAT_INS_ID VARCHAR2(32)，
LIC_NO VARCHAR2(50)，
SCHOOL_CONTRACT_UNI_SCID VARCHAR2(18)，
SCHOOL_CONTRACT_NAME VARCHAR2(500)，
DATE_BASE_TIME DATETIME，
DW_ETL_CREATE_TIME TIMESTAMP,
DW_ETL_UPDATE_TIME TIMESTAMP,
CONSTRAINT "GJZJ_SPJY_NEW_SCHOOL_ID" NOT CLUSTER PRIMARY KEY (ID)
);
COMMENT ON TABLE DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL IS '推送国家总局食品经营报告信息表';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL.ID IS '主键';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL.CERTIFICAT_INS_ID IS '证照实例id';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL.LIC_NO IS '许可证编号';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL.SCHOOL_CONTRACT_UNI_SCID IS '学校承包食堂的承包企业统一社会信用代码';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL.SCHOOL_CONTRACT_NAME IS '学校承包食堂的承包企业名称';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL.DATE_BASE_TIME IS '入库时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL.DW_ETL_CREATE_TIME IS 'ETL创建时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SCHOOL.DW_ETL_UPDATE_TIME IS 'ETL更新时间';

CREATE TABLE DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM(
ID VARCHAR2(32),
CERTIFICAT_INS_ID VARCHAR2(32),
LIC_NO VARCHAR2(50),
BUS_ITEM_CODE VARCHAR2(500),
BUS_ITEM VARCHAR2(500),
ND_BUS_ITEM_CODE VARCHAR2(500),
ND_BUS_ITEM VARCHAR2(500),
DATE_BASE_TIME DATETIME,
DW_ETL_CREATE_TIME TIMESTAMP,
DW_ETL_UPDATE_TIME TIMESTAMP,
CONSTRAINT "GJZJ_SPJY_NEW_SPECIAL_BUSITEM_ID" NOT CLUSTER PRIMARY KEY (ID)
);
COMMENT ON TABLE DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM IS '推送国家总局食品经营经营项目详细表';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.ID IS '主键';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.CERTIFICAT_INS_ID IS '证照实例id';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.LIC_NO IS '许可证编号';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.BUS_ITEM_CODE IS '一级经营项目代码';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.BUS_ITEM IS '一级经营项目';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.ND_BUS_ITEM_CODE IS '二级经营项目代码';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.ND_BUS_ITEM IS '二级经营项目';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.DATE_BASE_TIME IS '入库时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.DW_ETL_CREATE_TIME IS 'ETL创建时间';
COMMENT ON COLUMN DC_PERMIT.GJZJ_SPJY_NEW_SPECIAL_BUSITEM.DW_ETL_UPDATE_TIME IS 'ETL更新时间';
