CREATE TABLE "DC_CHECK"."ENT_BASE_TZSB_SBXX_JW"
(
"ID" VARCHAR2(32) NOT NULL,
"SBZCDM" VARCHAR2(200),
"QYMC" VARCHAR2(200),
"TYSHXYDM" VARCHAR2(200),
"SBXXDZ" VARCHAR2(300),
"ADCODE" VARCHAR2(20),
"EXTTYPE" VARCHAR2(50),
"LNG" VARCHAR2(50),
"LAT" VARCHAR2(50),
"LASTDATE" DATETIME(6),
"XH" BIGINT,
"ADDRESS" VARCHAR2(4000),
"KEY_PREFIX" VARCHAR2(4000),
"DW_ETL_CREATE_TIME" TIMESTAMP(6),
"DW_ETL_UPDATE_TIME" TIMESTAMP(6),
CONSTRAINT "DC_SUPERVISE.ENT_BASE_TZSB_SBXX_JW.ID" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

ALTER TABLE "DC_CHECK"."ENT_BASE_TZSB_SBXX_JW"
ADD COLUMN "DATE_TIME" TIMESTAMP