CREATE TABLE "DC_CHECK"."RA_MER_MEMBER"
(
"APPOINTUNIT" VARCHAR2(1600),
"LASTDATE" TIMESTAMP(6),
"LICFLAG" VARCHAR2(1024),
"OFFHFROM" DATE,
"OFFHTO" DATE,
"PERSONID" VARCHAR2(1024),
"POSBRFORM" VARCHAR2(64),
"POST" VARCHAR2(128),
"PRIPID" VARCHAR2(768),
"RECID" VARCHAR2(1024),
"ID" VARCHAR2(1024),
"MAIN_TB_ID" VARCHAR2(1024),
"CHIOFTHEDELSIGN" VARCHAR2(768)) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE DC_REGISTER.RA_MER_MEMBER IS '主要人员信息';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."APPOINTUNIT" IS '委派单位（无对应）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."CHIOFTHEDELSIGN" IS '首席代表标志';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."ID" IS '主键编号UUID D 01909';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."LASTDATE" IS '时间戳（原S_EXT_TIMESTAMP），D 01285，YYYYMMDDHHMMSS';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."MAIN_TB_ID" IS '企业基本信息表主键';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."OFFHFROM" IS '任职起始日期 D 00005  YYYYMMDD';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."OFFHTO" IS '任职截止日期 D 00010 YYYYMMDD';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."PERSONID" IS '人员记录ID（无对应）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."POSBRFORM" IS '职务产生方式,CB19  D 00009  采用代码集C00006中的代码';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."POST" IS '职务,CB18 （原POSITION）D 00004   采用代码集C00005中的代码';
COMMENT ON COLUMN DC_REGISTER.RA_MER_MEMBER."PRIPID" IS '主体身份代码 D 00269  采用代码集C00019中的代码';

ALTER TABLE "DC_CHECK"."RA_MER_MEMBER"
ADD COLUMN "DATE_TIME" TIMESTAMP

