CREATE TABLE "DC_REGISTER"."RA_MER_BASE"
(
"APPRDATE" DATE,
"BLICCOPYNUM" NUMBER,
"CURRENCY" VARCHAR2(96),
"DOM" VARCHAR2(9600),
"DOMCODE" VARCHAR2(1600),
"DOMDISTRICT" VARCHAR2(224),
"ENTCAT" VARCHAR2(360),
"ENTNAME" VARCHAR2(6400),
"ENTSTATUS" NUMBER,
"ENTTYPE" VARCHAR2(160),
"ESTDATE" DATE,
"INDUSTRYCO" VARCHAR2(160),
"INDUSTRYPHY" VARCHAR2(192),
"LASTDATE" TIMESTAMP(6),
"LEREP" VARCHAR2(3200),
"OPETYPE" VARCHAR2(320),
"OPFROM" DATE,
"OPFYEARS" NUMBER(18,6),
"OPSCOPE" VARCHAR2(32767),
"OPTO" DATE,
"PRIPID" VARCHAR2(768),
"RECID" VARCHAR2(1024),
"REGCAP" NUMBER(18,6),
"REGNO" VARCHAR2(800),
"REGORG" VARCHAR2(960),
"REMARK" VARCHAR2(32000),
"UNIFSOCICREDIDEN" VARCHAR2(576),
"ID" VARCHAR2(1024) NOT NULL,
"LICENSE_TYPE" VARCHAR2(640),
"ESTDATE1" DATE,
"DW_ETL_CREATE_TIME" TIMESTAMP(6),
"DW_ETL_UPDATE_TIME" TIMESTAMP(6),
CONSTRAINT "PK_RA_MER_MEMBER" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE DC_REGISTER.RA_MER_BASE IS '企业登记基本信息';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."APPRDATE" IS '核准日期，D 00658，YYYYMMDD';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."BLICCOPYNUM" IS '副本数（原CONUM），D 00377';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."CURRENCY" IS '币种D 00277，采用代码集C00013中的代码。';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."DOM" IS '住所，D 00272（原200）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."DOMCODE" IS '住所编码（新增），（没有对应）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."DOMDISTRICT" IS '住所所在行政区划,D 00274，采用代码集C00010中的代码。';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."ENTCAT" IS '企业类别,（没有对应）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."ENTNAME" IS '企业(机构)名称D 00270';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."ENTSTATUS" IS '企业状态,（没有对应）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."ENTTYPE" IS '企业(机构)类型，D 00282，采用代码集C00021中的代码';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."ESTDATE" IS '成立日期，D 00283，YYYYMMDD';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."ID" IS '主键编号UUID D 01909';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."INDUSTRYCO" IS '行业代码,D 00286，采用代码集C00015中的代码。';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."INDUSTRYPHY" IS '行业门类,D 00301，采用代码集C00014中的代码。';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."LASTDATE" IS '时间戳，D 01285，YYYYMMDDHHMMSS';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."LEREP" IS '法定代表人D 00275';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."OPETYPE" IS '企业类型大类,（没有对应）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."OPFROM" IS '经营(驻在)期限自，D 00284，YYYYMMDD';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."OPFYEARS" IS '营业期限（年限）,（没有对应）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."OPSCOPE" IS '经营(业务)范围（原BUSSCOPE）,D 00290';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."OPTO" IS '经营(驻在)期限至，D 00285，YYYYMMDD';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."PRIPID" IS '主体身份代码 D 00269  采用代码集C00019中的代码。';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."REGCAP" IS '注册资本（金信标准）D 00276';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."REGNO" IS '注册号D01874';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."REGORG" IS '登记机关,D 00287，采用代码集C00017中的代码。';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."REMARK" IS '备注，D 00828（原500）';
COMMENT ON COLUMN DC_REGISTER.RA_MER_BASE."UNIFSOCICREDIDEN" IS '统一社会信用代码（国家局标准是UNISCID） D 01765';

ALTER TABLE "DC_REGISTER"."RA_MER_BASE"
ADD COLUMN "DATE_BASE" DATESTAMP
